# Generated by Django 6.0 on 2025-12-07 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
