# Generated by Django 6.0 on 2025-12-07 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_menu_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='sistema_aberto',
            field=models.BooleanField(default=False),
        ),
    ]
